### ISSUE TITLE
Travis not working

### ISSUE THREAD

**Issue by davidgraeff** [homieiot/convention-website#1]
@marvinroger Could you please check if travis has organisation access? I cannot get it to work with the new Travis Marketplace Github App (which is different than the travis-ci github service from before).

It maybe only works for orga members, if that is the case, can you please go to the "Marketplace" in the top menu of Github, select travis, allow access and trigger a build for this repository. Thanks :)

**Comment by marvinroger** [comment]
It should be OK. The build fails, though: https://travis-ci.com/homieiot/website-redesign/builds/89436588

**Comment by marvinroger** [comment]
I'll fix and deploy. 😉

**Comment by marvinroger** [comment]
Deployed: https://homieiot.github.io/ 👍 
Thanks a lot!
