### ISSUE TITLE
Difference between OCF/Iotivity/WebThing API & Homie

### ISSUE THREAD

**Issue by marvinroger** [homieiot/convention-website#2]
_From @echo1consulting on May 29, 2017 2:4_

Hello, are you familiar with [OCF](https://openconnectivity.org/) and [Iotivity](https://www.iotivity.org/)?

It seems that there are similarities in the mission of Homie and OCF. 

_Copied from original issue: homieiot/convention#22_

**Comment by marvinroger** [comment]
Hi!

I don't, but yes, the end goal is the same: try to "standardize" how IoT devices work. But if you know more about OCF and Iotivity and given the fact that Homie is a rather short document, maybe you are in the best position to explain what are the differences. 😉

**Comment by marvinroger** [comment]
_From @davidgraeff on October 29, 2018 7:10_

Should this be mentioned on the website somewhere? There is also https://iot.mozilla.org/wot/ as a 3rd alternative spec.

**Comment by marvinroger** [comment]
I’m for openness, so yes. It might even help for Homie adoption, as people would be able to quickly compare the alternatives.

**Comment by marvinroger** [comment]
_From @davidgraeff on October 29, 2018 7:55_

@marvinroger Could you use https://github-issue-mover.appspot.com/ or similar to move this Issue to the webpage repo?

**Comment by davidgraeff** [comment]
I have decided to not include this on the web page, because it is not related.
* OCF (Iotivity) is for CoAP.
* WebThing is for REST CRUDN interfaces like http+websocket.
