### ISSUE TITLE
Validator crashes

### ISSUE THREAD

**Issue by KeKsBoTer** [homieiot/convention-website#46]
Hello,

pasting the following code into the validator results in a crash:
```
homie/device123/$homie 4.0
homie/device123/$name My device
homie/device123/$state ready
homie/device123/$extensions 
homie/device123/$nodes mythermostat
homie/device123/$state/set init
```

The exception printed to the JavaScript console is the following:
```
Uncaught ReferenceError: value is not defined
    homieverificator https://homieiot.github.io/js/main.min.js:54
    homieverificator https://homieiot.github.io/js/main.min.js:54
    onclick https://homieiot.github.io/tools/#:1
main.min.js:54:162
    homieverificator https://homieiot.github.io/js/main.min.js:54
    forEach self-hosted:206
    homieverificator https://homieiot.github.io/js/main.min.js:54
    onclick https://homieiot.github.io/tools/#:1
```

To be honest I am not sure if calling `/set`on a device property is even allowed, but I did not find anything about it in the specification.

Nevertheless this should not result in the validator crashing.

**Comment by Thalhammer** [comment]
> To be honest I am not sure if calling /seton a device property is even allowed

It is allowed for properties, however `$state` is a node attribute (as indicated by the `$`), where it is not allowed on.
That said you are right, it should not cause a crash.
