### ISSUE TITLE
[Bug] Settable attribute is not specified in the example of the "Overview" section

### ISSUE THREAD

**Issue by bodiroga** [homieiot/convention-website#9]
Hi @davidgraeff!

I'm not sure if this issue belongs here, but I have noticed that, in the Overview section of the webpage (https://homieiot.github.io/), the provided example doesn't have the "settable" attribute defined for its "temperature" property. The example description states that "_the target temperature can be read from and written to._", so settable should be set to true. At the same time, the "extension" device attribute is published, but this is not part of the latest stable release.

Thanks and best regards,

Aitor

**Comment by davidgraeff** [comment]
True. The topic name with the underbar is also not according to the convention. I noticed that when I tried to use the example on the validator.
